### ISSUE TITLE
Drop down menu in /order

### ISSUE THREAD

**Issue by MaksimPas** [seel93/prosjektOppgaveGruppe2#4]
Det går an å legge til samme sykkel flere ganger fra drop down menu. F eks sykkelen "testnavn1" kan velges flere ganger fra drop down menu.
![image](https://user-images.githubusercontent.com/33008899/39776599-febd73d4-5309-11e8-8574-79e7c603da96.png)

**Comment by seel93** [comment]
Fikset. Sjekker array.includes() på element som allerede ligger i arrayen med valgt utstyr eller sykkel.
